# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/ruoyi-yaman?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
                username: root
                password: mDjs2022Pwd
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
            statViewServlet:
                # 控制台管理用户名和密码
                login-username: root
                login-password: mDjs2022Pwd
    # redis 配置
    redis:
        host: 127.0.0.1
        # 端口，默认为6379
        port: 6379
        # 密码
        password: yyds123
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
ruoyi:
    # 文件路径 示例（ Windows配置C:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
    profile: /home/ruoyi/uploadPath
scheduling:
    enabled: false
#操作oss需要的一些参数
aliyun:
    accessKeyId:        # 阿里云的accessKeyId
    secretAccessKey:    # accessKey 密码
    oss:
        endPoint:      # Endpoint:在阿里云oss控制台查看自己使用的endpoint
        bucketName:    # bucket 名称
wechat:
    enabled: false
    appId: 你的微信服务号信息（h5的时候需要，小程序的时候不需要）
    secret: 你的微信服务号信息（h5的时候需要，小程序的时候不需要）
    merchantId: 微信支付商户号
    privateKeyPath: 微信支付密钥地址相对地址
    merchantSerialNumber: 微信支付密钥对应的序列号
    apiV3key: 微信支付apiV3key
    notifyUrl: 微信支付回调地址
    miniProgramAppId: 小程序apppid（h5的时候不需要）
    miniProgramSecret: 小程序Secret（h5的时候不需要）
sms:
    enabled: true
    # 阿里云 dysmsapi.aliyuncs.com
    endpoint: dysmsapi.aliyuncs.com
    accessKeyId: 你的accessKeyId #阿里云短信服务控制台查看
    accessKeySecret: 你的accessKeySecret #同上
    signName:  签名
    templateId: 模板id
    # 腾讯专用
    sdkAppId:
aes:
    # aes的密钥(长度只能是16或24或32位)
    key: 1111111111111111
knife4j:
    basic:
        enable: true
        username: xmmry
        password: xmmry