# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/ruoyi-yaman?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
                username: root
                password: mDjs2022Pwd
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
            statViewServlet:
                # 控制台管理用户名和密码
                login-username: root
                login-password: mDjs2022Pwd
    # redis 配置
    redis:
        host: 127.0.0.1
        # 端口，默认为6379
        port: 6379
        # 密码
        password: yyds123
        timeout: 10s
        lettuce:
            pool:
                # 连接池中的最小空闲连接
                min-idle: 0
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池的最大数据库连接数
                max-active: 8
                # #连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
ruoyi:
    # 文件路径 示例（ Windows配置C:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
    profile: /data/uploadPath
scheduling:
    enabled: true
#操作oss需要的一些参数
aliyun:
    accessKeyId:        # 阿里云的accessKeyId
    secretAccessKey:    # accessKey 密码
    oss:
        endPoint:      # Endpoint:在阿里云oss控制台查看自己使用的endpoint
        bucketName:    # bucket 名称
aes:
    # aes的密钥(长度只能是16或24或32位)
    key: 1111111111111111
knife4j:
    enable: true
    # 开启生产环境屏蔽
    production: false
    basic:
        enable: true
        username: xmmry
        password: xmmry